replicaCount: 1

image:
  repository: dpage/pgadmin4
  tag: "8.13"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: pgadmin.localtest.me
      paths:
        - path: /
          pathType: Prefix
  tls: []

credentials:
  username: "admin@example.com"
  password: "admin1234"

serversJson:
  enabled: true
  servers:
    Servers:
      "1":
        Name: "Local Postgres"
        Group: "Servers"
        Host: "postgresql.postgres.svc.cluster.local"
        Port: 5432
        MaintenanceDB: "coder"
        Username: "coder"
        SSLMode: "prefer"

persistence:
  enabled: true
  size: 2Gi
  storageClass: ""

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

readinessProbe:
  enabled: true
  httpGet:
    path: /misc/ping
    port: 80
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 6

livenessProbe:
  enabled: true
  httpGet:
    path: /login
    port: 80
  initialDelaySeconds: 120
  periodSeconds: 30
  timeoutSeconds: 80
  failureThreshold: 80

startupProbe:
  enabled: true
  httpGet:
    path: /login
    port: 80
  initialDelaySeconds: 300 
  failureThreshold: 30
  periodSeconds: 10

podSecurityContext:
  enabled: true
  fsGroup: 5050
  fsGroupChangePolicy: "OnRootMismatch"

securityContext:
  enabled: true
  runAsUser: 5050
  runAsGroup: 5050
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false  # doit rester false pour pgAdmin

pdb:
  enabled: true
  minAvailable: 1

autoscaling:
  enabled: true            # active le HPA
  minReplicas: 1           # nombre minimal de pods
  maxReplicas: 5           # nombre maximal de pods
  targetCPUUtilizationPercentage: 70      # scale si CPU > 70%
  targetMemoryUtilizationPercentage: 80   # scale si mémoire > 80%
