apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgadmin.fullname" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pgadmin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pgadmin.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: pgadmin4
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          {{- if .Values.securityContext.enabled }}
          securityContext:
            {{- omit .Values.securityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "pgadmin.fullname" . }}-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/pgadmin
            - name: servers
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            {{- omit .Values.startupProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "pgadmin.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: servers
          configMap:
            name: {{ include "pgadmin.fullname" . }}-servers
