apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgadmin4.fullname" . }}-secret
  labels:
    {{- include "pgadmin4.labels" . | nindent 4 }}
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: {{ .Values.credentials.username | quote }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.credentials.password | quote }}
